locals {
  definitions = {
    tags = { ManagedBy = "Terraform" }

    validator_expressions = {
      "client_affinity_enabled"                        = "^(true|false)$"
      "client_certificate_enabled"                     = "^(true|false)$"
      "client_certificate_mode"                        = "^(Required|Optional|OptionalInteractiveUser)$"
      "default"                                        = ".*"
      "enabled"                                        = "^(true|false)$"
      "ftp_publish_basic_authentication_enabled"       = "^(true|false)$"
      "https_only"                                     = "^(true|false)$"
      "location"                                       = "^(southafricanorth|southafricawest|australiacentral|australiacentral2|australiaeast|australiasoutheast|centralindia|eastasia|japaneast|japanwest|jioindiacentral|jioindiawest|koreacentral|koreasouth|newzealandnorth|southindia|southeastasia|westindia|canadacentral|canadaeast|francecentral|francesouth|germanynorth|germanywestcentral|italynorth|northeurope|norwayeast|norwaywest|polandcentral|spaincentral|swedencentral|switzerlandnorth|switzerlandwest|uksouth|ukwest|westeurope|mexicocentral|israelcentral|qatarcentral|uaecentral|uaenorth|brazilsouth|brazilsoutheast|brazilus|centralus|centraluseuap|eastus|eastus2|eastus2euap|eastusstg|northcentralus|southcentralus|southcentralusstg|westcentralus|westus|westus2|westus3)$"
      "os_type"                                        = "^(Windows|Linux|WindowsContainer)$"
      "per_site_scaling_enabled"                       = "^(true|false)$"
      "public_network_access_enabled"                  = "^(true|false)$"
      "resource_tags"                                  = "^[a-zA-Z0-9_\\-\\.]{1,512}$"
      "sku_name"                                       = "^(B1|B2|B3|D1|F1|I1|I2|I3|I1v2|I2v2|I3v2|I4v2|I5v2|I6v2|P1v2|P2v2|P3v2|P0v3|P1v3|P2v3|P3v3|P1mv3|P2mv3|P3mv3|P4mv3|P5mv3|S1|S2|S3|SHARED|EP1|EP2|EP3|FC1|WS1|WS2|WS3|Y1)$"
      "timeout"                                        = "^(create|read|update|delete)$"
      "webdeploy_publish_basic_authentication_enabled" = "^(true|false)$"
      "worker_count"                                   = "^[0-9]+$"
      "site_config.always_on"                          = "^(true|false)$"
      "site_config.ftps_state"                         = "^(AllAllowed|FtpsOnly|Disabled)$"
      "site_config.health_check_eviction_time_in_min"  = "^([2-9]|10)$"
      "site_config.load_balancing_mode"                = "^(WeightedRoundRobin|LeastRequests|LeastResponseTime|WeightedTotalTraffic|RequestHash|PerSiteRoundRobin)$"
      "site_config.local_mysql_enabled"                = "^(true|false)$"
      "site_config.managed_pipeline_mode"              = "^(Integrated|Classic)$"
      "site_config.minimum_tls_version"                = "^(1\\.0|1\\.1|1\\.2|1\\.3)$"
      "site_config.remote_debugging_enabled"           = "^(true|false)$"
      "site_config.remote_debugging_version"           = "^VS2022$"
      "site_config.scm_minimum_tls_version"            = "^(1\\.0|1\\.1|1\\.2)$"
      "site_config.scm_use_main_ip_restriction"        = "^(true|false)$"
      "site_config.use_32_bit_worker"                  = "^(true|false)$"
      "site_config.vnet_route_all_enabled"             = "^(true|false)$"
      "site_config.websockets_enabled"                 = "^(true|false)$"
      "site_config.worker_count"                       = "^[0-9]+$"
    }

    validator_error_messages = {
      "client_affinity_enabled"                        = "The client_affinity_enabled variable must be true or false."
      "client_certificate_enabled"                     = "The client_certificate_enabled variable must be true or false."
      "client_certificate_mode"                        = "The client_certificate_mode must be one of: Required, Optional, or OptionalInteractiveUser."
      "default"                                        = "Unknown error during validation has occured."
      "enabled"                                        = "Err: A boolean variable is restricted to true or false."
      "ftp_publish_basic_authentication_enabled"       = "Err: A boolean variable is restricted to true or false."
      "https_only"                                     = "Err: A boolean variable is restricted to true or false."
      "location"                                       = "The location must be a valid Azure region."
      "os_type"                                        = "The os_type variable must be one of: Windows, Linux, or WindowsContainer."
      "per_site_scaling_enabled"                       = "The per_site_scaling_enabled variable must be true or false."
      "public_network_access_enabled"                  = "Err: A boolean variable is restricted to true or false."
      "resource_tags"                                  = "Resource tag keys and values must follow Azure naming conventions."
      "sku_name"                                       = "The sku_name variable must be one of the allowed SKU values as per official documentation."
      "timeout"                                        = "Timeout key must be one of create, read, update, or delete, and value must follow format like 30m, 1h etc."
      "webdeploy_publish_basic_authentication_enabled" = "Err: A boolean variable is restricted to true or false."
      "worker_count"                                   = "The worker_count must be a non-negative integer."
      "site_config.always_on"                          = "The site_config.always_on value must be true or false. If using Free, F1, D1 or Shared plan, it must be explicitly set to false."
      "site_config.ftps_state"                         = "The site_config.ftps_state value must be one of: AllAllowed, FtpsOnly, or Disabled."
      "site_config.health_check_eviction_time_in_min"  = "The site_config.health_check_eviction_time_in_min must be an integer between 2 and 10 (inclusive)."
      "site_config.load_balancing_mode"                = "The site_config.load_balancing_mode must be one of: WeightedRoundRobin, LeastRequests, LeastResponseTime, WeightedTotalTraffic, RequestHash, or PerSiteRoundRobin."
      "site_config.local_mysql_enabled"                = "The site_config.local_mysql_enabled value must be true or false."
      "site_config.managed_pipeline_mode"              = "The site_config.managed_pipeline_mode value must be one of: Integrated or Classic."
      "site_config.minimum_tls_version"                = "The site_config.minimum_tls_version value must be one of: 1.0, 1.1, 1.2, or 1.3."
      "site_config.remote_debugging_enabled"           = "The site_config.remote_debugging_enabled value must be true or false."
      "site_config.remote_debugging_version"           = "The site_config.remote_debugging_version value must be VS2022."
      "site_config.scm_minimum_tls_version"            = "The site_config.scm_minimum_tls_version value must be one of: 1.0, 1.1, or 1.2."
      "site_config.scm_use_main_ip_restriction"        = "The site_config.scm_use_main_ip_restriction value must be true or false."
      "site_config.use_32_bit_worker"                  = "The site_config.use_32_bit_worker value must be true or false."
      "site_config.vnet_route_all_enabled"             = "The site_config.vnet_route_all_enabled value must be true or false."
      "site_config.websockets_enabled"                 = "The site_config.websockets_enabled value must be true or false."
      "site_config.worker_count"                       = "The site_config.worker_count value must be a non-negative integer."
    }
  }
}
